name: Test Action
runs:
  using: composite
  steps:
    - name: Test normal path
      shell: bash
      run: |
        echo $PWD
        ls -l
    - name: Test action path
      working-directory: ${{ env.GITHUB_ACTION_PATH }}
      shell: bash
      run: |
        echo $GITHUB_ACTION_PATH
        ls -l
